version: '3.8'

services:
  postgres-commandes:
    image: postgres:15-alpine
    container_name: gestion-commandes-db
    restart: always
    environment:
      POSTGRES_USER: commande_user
      POSTGRES_PASSWORD: commande_password
      POSTGRES_DB: gestion_commandes_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_commandes_data:/var/lib/postgresql/data
    networks:
      - commandes-network

networks:
  commandes-network:
    driver: bridge

volumes:
  postgres_commandes_data: 